databases:
  - name: itobakery_DB
    databaseName: itobakery_db
    user: itobakery
    region: singapore

services:
  - type: web
    name: itobakery
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itobakery_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

